name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: جلب ملفات المشروع
        uses: actions/checkout@v4

      - name: بناء تطبيق الأندرويد باستخدام Flet Action
        uses: flet-dev/flet-build-action@v1
        with:
          target: apk
          runner-python-version: "3.11"
          build-number: ${{ github.run_number }}

      - name: رفع ملف الـ APK النهائي
        uses: actions/upload-artifact@v4
        with:
          name: LG-Remote-App-APK
          path: |
            build/apk/**/*.apk
            build/app/outputs/flutter-apk/*.apk
